### PR TITLE
lazy load inputs and outputs [risk: low]

### LINKED ISSUE #231: Columns swapped past 1st page of workflow input display
Under the Monitor tab, within the Workflow Inputs list, if you go past the first page, the Task and Label column values are incorrect in some instances. [Image](https://us.v-cdn.net/5019796/uploads/editor/ob/tb856ja10lc4.png) from user's [post](https://gatkforums.broadinstitute.org/firecloud/discussion/23168/bug-report-listing-of-workflow-input-display-incorrect-after-first-page#latest) shows second page of their workflow inputs where the Task and Label are not correct. 

Additionally, we should show the Task column for subworkflows; currently this is hidden. Since subworkflows can have many tasks, this is a worthwhile column there.

### PR DESCRIPTION
**Pull request by davidangb**
DataBiosphere/firecloud-app#215
also fixes DataBiosphere/firecloud-app#231 while I'm in there

Goal of this PR is lighten the initial workflow metadata query to not retrieve inputs or outputs info, thus making it smaller; and then only request the input/output data on demand if a user chooses to expand one of those sections.

On the workflow detail page, we have:
* 1 `WorkflowDetails` component, which contains:
  * 1-N `CallDetail` components, which contain:
    * 0-N `IODetail` components
    * 0-N `WorkflowDetails` components to handle subworkflows (yes this recurses)

Previously, the `WorkflowDetails` component made a single request for workflow metadata + inputs + outputs, then passed data down the tree as props into children `IODetail`s, which handle display of inputs and outputs..

In this PR, the `WorkflowDetails` component requests the main metadata and passes it as props to child `IODetails`. It also passes separate - initially nil - props for input data and output data, as well as an `input-fn` and an `output-fn`, which are references to functions defined on the `WorkflowDetails` component . When any child `IODetails` needs to display input or output data, the child component executes the `input-fn`/`output-fn`. This triggers the `WorkflowDetails` to make an additional ajax request for the appropriate data, which it caches in its state. React handles automatically updating the child components, via props, with the updated data.

We only load subworkflow information on demand, once a user expands to see the subworkflow. Previously, we had separate functions/components to handle subworkflows, which means I would have had to implement the same kind of state-lifting logic in the subworkflow components. Instead, I have deleted the subworkflow-specific component/function and driven it all through `WorkflowDetails`, so subworkflows automatically inherit the lazy-loading of inputs/outputs.

-----
   

- [x] **Submitter**: Include the JIRA issue number in the PR description
- [x] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [x] **Submitter**: If you changed a URL that is used elsewhere (e.g. in an email), comment about where it is used and ensure the dependent code is updated.
- [x] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * To Demo flag is set
  * Release Summary is filled out, if applicable
  * Add notes on how to QA
- [x] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [x] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [x] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [x] **Submitter**: If you're adding new automated UI tests, review the test plan with QA
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [x] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Submitter**: Verify all tests go green, including CI tests and automated UI tests.
- [ ] **Submitter**: Squash commits and merge to develop. If adding test code, merge application code and test code at the same time.
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

### CODE REVIEW

File: src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs [hunk 1]
```diff
@@ -64,30 +69,43 @@
...
+       [:div {}
+        (create-field
+         (:label props)
+           (links/create-internal {:onClick #(swap! state update :expanded not)}
+             (if (:expanded @state) "Hide" "Show")))
+        (when (:expanded @state)
+          (cond
+            (nil? data)
+              (do
+                (data-fn) ;; trigger the request to get data
```
Comment (breilly2) [inline src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs]: Could this be triggered from `onClick` rather than waiting for a render cycle?

File: src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs [hunk 2]
```diff
@@ -363,46 +338,60 @@
...
      (when (seq (workflow "calls"))
        [WorkflowTimingContainer (merge {:label "Workflow Timing"} (utils/restructure workspace-id submission-id workflow))])
      (when-let [failures (workflow "failures")]
        [Failures {:data failures}])
      (when (seq (workflow "calls"))
        [:div {:style {:marginTop "1em" :fontWeight 500}} "Calls:"])
      (for [[call data] (workflow "calls")]
-       [CallDetail {:label call :data data :submission-id submission-id :use-call-cache use-call-cache :workflowId (workflow "id")
-                    :workspace-id workspace-id :gcs-path-prefix workflow-path-components}])]))
+        [CallDetail (conj (utils/restructure data submission-id use-call-cache workspace-id
```
Comment (breilly2) [inline src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs:378]: Nice! I like this technique of avoiding the repetition where possible.

File: src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs [hunk 3]
```diff
@@ -64,30 +69,42 @@
...
+          (cond
+            (nil? data)
+              (spinner (str "Loading " (:label props) "...")) ;; show a spinner while data from the onClick loads
+            (not (:success? data))
+              (style/create-inline-error-message (:response data))
+            (empty? (get-in data (cons :response data-path)))
+              [:div {:style {:padding "0.25em 0 0.5em 1em" :font-style "italic"}} (str "No " (:label props) ".")]
+            :else
+              ;; some portions of the metadata response from Cromwell are escaped json strings (e.g. submittedFiles/inputs),
+              ;; instead of valid json. hHndle that transparently here: if we detect the target data is a string, attempt to parse it.
```
Comment (breilly2) [inline src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs]: Nit: typo "hHndle"

File: src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs [hunk 4]
```diff
@@ -412,7 +399,11 @@
          (let [workflow-path-prefix [(:bucketName props) (:submission-id props)]]
            (render-workflow-detail (:response metadata-response) (:raw-response metadata-response)
                                    (:workflow-name props) (:submission-id props) (:use-call-cache props)
-                                   (:workspace-id props) workflow-path-prefix)))))
+                                   (:workspace-id props) workflow-path-prefix
+                                   #(this :get-inputs) (:metadata-inputs @state)
+                                   #(this :get-outputs) (:metadata-outputs @state)
+                                   (:subworkflow? props)
+                                   )))))
```
Comment (breilly2) [inline src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs]: Nit: ')'s should be joined with the line above, I think

**Review by breilly2 — APPROVED** [review]
👍 Nice work here! I always appreciate the thorough PR descriptions. Makes it easy to understand the intent of the work.

**Comment by davidangb** [comment]
One `Request Timed Out` error in an unrelated test. I'll re-run it manually:
```
[info] Tests: succeeded 128, failed 1, canceled 0, ignored 7, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	org.broadinstitute.dsde.firecloud.test.analysis.MethodImportSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
```

EDIT: the failed test passed in the manual run: https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/14051/

File: src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs [hunk 5]
```diff
@@ -34,12 +35,20 @@
...
 
 (defonce metadata-timing-includes ["attempt" "description" "end" "endTime" "executionEvents" "executionStatus"
                                    "shardIndex" "start" "startTime" "workflowName"])
 
+(defonce metadata-inputs-includes ["submittedFiles:inputs" "inputs"])
+
+;; requesting executionStatus for outputs makes the response payload somewhat larger, but it forces Cromwell to return
+;; data about every call in a task scatter. Otherwise, if we request just includeKey=outputs and a scatter contains both
+;; successes and failures, Cromwell will return only those calls that have outputs, i.e. the successes. Since our CLJS code
+;; identifies calls by their index in an array, this causes off-by-one (or off-by-many) functional errors.
```
Comment (breilly2) [inline src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs:49]: Good catch! *Ugh* about the parallel arrays. Without thinking about it too much more, I can imagine that "that's just the way it is" and there isn't a better way to handle this. Curious if there is a better solution that just isn't worth investing the energy to implement.

Comment (davidangb) [reply src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs:49]: you caught me - there is a potentially better way that I didn't want to implement - both b/c of development effort and risk of error. I *could* inspect the array for missing shards and insert them and/or use a function to extract a matching shard instead of relying on the array index. Both of these felt too easy to get wrong, so I felt this was overall the right solution.

**Review by breilly2 — APPROVED** [review]
👍 Didn't test the latest changes because it seems like you have it well in hand and I wasn't sure how to create the right conditions. Thank you for adding the comments about why.

File: src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs (hunk 5 above)
Comment (breilly2) [reply src/cljs/main/broadfcui/page/workspace/monitor/workflow_details.cljs:49]: It works for me, especially since you've explicitly documented that array order dependency which someone might otherwise miss.

**Comment by davidangb** [comment]
dockerhub failure during test; jenkins retest.
